### ISSUE TITLE
Pdf export vector quality

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [pierremarc/extruder#12]
When we export the word to a pdf (knockout) we get little artifacts in the letter shapes.
There seems to be an outline on some of the paths causing these artifacts. When I manually set stroke to none in Adobe Illustrator all artifacts are gone and the letter shapes are clean. See screenshots.
Can we get rid of the outline strokes?

Output from the app
<img width="926" alt="schermafbeelding 2017-02-20 om 11 54 31" src="https://cloud.githubusercontent.com/assets/1528770/23122264/ce9261ea-f763-11e6-8df5-83dcf173314c.png">
Manually removed strokes
<img width="985" alt="schermafbeelding 2017-02-20 om 11 54 51" src="https://cloud.githubusercontent.com/assets/1528770/23122377/3961c2ae-f764-11e6-9606-e278f140f149.png">

**Comment by JeroenHoutmeyers** [comment]
We found another issue with the numbers:
When you type a 1 or 2 and export to pdf (knockout) we get distorted output.
See pdf attached.
[extruder-knockout.pdf](https://github.com/pierremarc/extruder/files/789546/extruder-knockout.pdf)

This looks like the same issue. c on second line gets messed up.
[extruder-knockout (3).pdf](https://github.com/pierremarc/extruder/files/789578/extruder-knockout.3.pdf)

**Comment by pierremarc** [comment]
I expected this. As said at the beginning, boolean operations are quite complex and I resorted to external libraries (paperjs) to perform them in this application. Unfortunately it often breaks and it's difficult to tell when. It's the reason why I made those 2 export options to keep a more reliable output. The latter being possibly processed with more mature software when knockout is desirable.

**Comment by JeroenHoutmeyers** [comment]
Ok, I guess your remark refers to my second comment?
Would have been just perfect usability wise if we could  have one pdf export to for all our needs.
Now we have one pdf and one transparent type pdf labeled experimental complicating things a bit. But I understand why of course. I need to discuss with my collegues and I'll get back to you, because if we have to keep the two pdf buttons I think we need to label them properly and provide some help text. 
Can you fix the first comment? This issue appears in both pdf options. Maybe the second comment should be a separate issue.
