### ISSUE TITLE
Longer text produces corrupt pdf files

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [pierremarc/extruder#17]
When placing a longer text in the textfield like this one:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate metus at odio fringilla, ut posuere ante luctus. Aliquam nisl mauris, ultrices a purus vitae, efficitur congue risus." The tool produces a corrupt pdf file.

**Comment by pierremarc** [comment]
An nginx issue with ```client_max_body_size``` configuration directive not set high enough
