### ISSUE TITLE
Rounded corners on type on pdf export

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [pierremarc/extruder#25]
We see rounded corners on the letter shapes. They actually get very prominent in PNG's extruded from small font sizes (see screenshot)

In the attached PPT, I tested PNG’s with different type sizes. It seems to look ok only from font sizes 330 upwards. PDF is less problematic, but has more extra lines visible.

Can you make corners straight?

This is caused by an outline on the type. We understand why it is there but the thickness of the outline is consistent throughout different font sizes redering the type much fatter in some cases.
Possible easy fix: What if we just put minimum type size much larger? Maybe minimum around 250?

![screen shot 2017-03-21 at 09 50 52](https://cloud.githubusercontent.com/assets/1528770/24145264/a6d075c8-0e30-11e7-9430-bd55045f3c1d.png)
[extruder_font_size_test.pptx](https://github.com/pierremarc/extruder/files/857926/extruder_font_size_test.pptx)

**Comment by pierremarc** [comment]
There are issues in the powerpoint document which are unavoidable, specifically upscaled images and weird PDF rendering.

I fixed the round joining issue and followed your suggestion to make the minimum font size much larger. But obviously there will be a need a bit for operators education/training to get the best results off of the application.

**Comment by JeroenHoutmeyers** [comment]
We see that you fixed the round joining issue, by removing the outline on the type.
Now some hairlines are visible in the pdf. Can we reintroduce the outline, but make the joining straight?

Turns out 250 minimum fontsize is to big, can we change it into 150?
