### ISSUE TITLE
line break text

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [pierremarc/extruder#5]
Text should  go to a next line when it reaches the edge of a defined point (where the canvas is now). Reference for the desired behavior: http://www.fontsmith.com/fonts/fs-albert/test-drive > click the ‘display’.

Type size can be limited to maximum 700

**Comment by pierremarc** [comment]
I've got to reopen it because of #6 asking for more than a fix on this.

**Comment by pierremarc** [comment]
Finally got a proper fix for it.
