### ISSUE TITLE
Export only the extruded text

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [pierremarc/extruder#6]
When exporting text, we should only get the text not the entire canvas.
We would like this behavior in png and pdf.
If possible, add some margin (about 100px) all the way around the text, so the export looks better

These are some examples:
![extruder 2 copy](https://cloud.githubusercontent.com/assets/1528770/23074737/2cb2041e-f53a-11e6-9b11-80be0b220c9e.png)
![extruder 3 copy](https://cloud.githubusercontent.com/assets/1528770/23074738/2cb2bde6-f53a-11e6-8928-e3c5a2ca1efb.png)
![extruder 4 copy](https://cloud.githubusercontent.com/assets/1528770/23074739/2cb3108e-f53a-11e6-87ea-8b64a9ec6944.png)

**Comment by pierremarc** [comment]
Still working on it.
It has asked for major refactoring  which is still ongoing.
